apiVersion: v1
kind: Service
metadata:

  labels:
    app: pgvector
  name: pgvector
  namespace: vectorator
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: pgvector