apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pgvectordata
  name: pgvectordata
  namespace: vectorator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
