apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: vectorizer
  name: vectorizer
  namespace: vectorator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vectorizer
  template:
    metadata:

      labels:
        app: vectorizer
    spec:
      containers:
        - env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_API_KEY
                  name: vectorator-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: vectorator-secrets
            - name: PGVECTOR_URI
              value: postgres:$POSTGRES_PASSWORD@pgvector:5432/vectorator
            # optional, uncomment if you want to use openai
            - name: OPENAI_BASE_URL
              value: "https://openrouter.ai/api/v1"
            - name: OPENAI_MODEL
              value: "meta-llama/llama-3.1-70b-instruct"
          image: guestros/langchain-vectorizer-webservice:latest
          name: vectorizer
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
