apiVersion: v1
kind: Service
metadata:

  labels:
    app: vectorizer
  name: vectorizer
  namespace: vectorator
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: vectorizer
